jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step
        run: |
          ! gofmt -l -s . | grep -q ''
          go vet ./...
          go test ./...
          go install ./...

name: workflow

'on':
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    # generated randomly
    - cron: '42 22 * * FRI'
